server:
  host: 0.0.0.0
  port: 8080
database:
  host: go-business-opening-hours-database
  port: 5432
  database: go-business-opening-hours
  searchpath: public
  user: go-business-opening-hours
  password: go-business-opening-hours
  version: 1.1.0
