version: "3.9"
services:
  go-business-opening-hours-application:
    container_name: go-business-opening-hours-application
    build: ./
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - go-business-opening-hours-network
  go-business-opening-hours-database:
    container_name: go-business-opening-hours-database
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=go-business-opening-hours
      - POSTGRES_USER=go-business-opening-hours
      - POSTGRES_PASSWORD=go-business-opening-hours
    ports:
      - 5432:5432
    networks:
      - go-business-opening-hours-network
  go-business-opening-hours-database-migrate:
    container_name: go-business-opening-hours-database-migrate
    image: flyway/flyway:8.5-alpine
    restart: on-failure
    command: -url=jdbc:postgresql://go-business-opening-hours-database:5432/go-business-opening-hours -schemas=public -user=go-business-opening-hours -password=go-business-opening-hours -connectRetries=60 migrate
    volumes:
      - ./migration:/flyway/sql
    networks:
      - go-business-opening-hours-network
networks:
  go-business-opening-hours-network:
